name: Pull Request Labeler

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Controls when the workflow will run
on:
  pull_request_target:
    types: [opened, edited, reopened]

env:
  MSDK_DIR: msdk
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The verify job will check the differences with any updated register file.
  label:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest ]

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Labeling
        uses: actions/labeler@v4
        with:
          sync-labels: true
