name: Build & Deploy Cordio Platform Docs

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - uses: actions/checkout@v3
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
          fetch-depth: 0

      - name: Generate Docs (MAX32655)
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: Libraries/Cordio/docs
          doxyfile-path: cordio_platform_doxyfile
          enable-latex: true

      - name: Build PDF
        run: |
          echo "Building PDF..."
          sudo apt-get install texlive-full
          sudo make -C Libraries/Cordio/docs/latex

          echo "Copying PDF to Cordio/platform/Documentation"
          sudo mv Libraries/Cordio/docs/latex/refman.pdf Libraries/Cordio/docs/latex/Cordio-Platform-Documentation.pdf
          sudo mkdir -p Libraries/Cordio/platform/Documentation && sudo cp -r Libraries/Cordio/docs/latex/Cordio-Platform-Documentation.pdf Libraries/Cordio/platform/Documentation/
          
          
      - name: Push Documentation Files
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: 'Libraries/Cordio/platform/Documentation/Platform_ref.pdf'
          message: 'Update documentation.'
          push: true



        
