#ifndef ECTF_PARAMS
#define ECTF_PARAMS
#define COMPONENT_ID 0x11111125
#define COMPONENT_BOOT_MSG "Component boot"
#define ATTESTATION_LOC "McLean"
#define ATTESTATION_DATE "08/08/08"
#define ATTESTATION_CUSTOMER "Fritz"
#endif /* ECTF_PARAMS */
